export 'User/splash_page.dart';
export 'User/sign_in_page.dart';
export 'User/sign_up_page.dart';
export 'User/home_page.dart';
export 'User/medicine_detail_page.dart';
export 'User/medicine_pick_page.dart';
export 'User/medicine_add_page.dart';
export 'User/news_detail_page.dart';
export 'User/pick_doctor_page.dart';
export 'User/detail_doctor_page.dart';
export 'User/setting_page.dart';
export 'User/article_history_page.dart';
export 'User/transaction_history_page.dart';
export 'User/detail_payment_page.dart';
export 'User/detail_payment_page_2.dart';
export 'User/payment_method.dart';
export 'User/forget_password_page.dart';
export 'User/rename_password_page.dart';
export 'User/profile_page.dart';
export 'User/medical_article_page.dart';
export 'User/chat_room_page.dart';
export 'User/map_screen_page.dart';
export 'User/chat_page.dart';
export 'Doctor only/home_page_doctor.dart';
export 'Doctor only/chat_room_page_doctor.dart';
export 'Doctor only/E-money.dart';
export 'Doctor only/payment_method_emoney.dart';
export 'Doctor only/nomor_rekening.dart';
export 'Doctor only/medicine_pick_page_doctor.dart';
export 'Doctor only/chat_page_doctor.dart';
export 'Doctor only/detail_doctor_page_doctor.dart';
