// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLhBJu-2ZsH6FbaCh0fzcOQ7wfnIAZfs',
    appId: '1:982208266428:web:65491bd5fd774cbea650b9',
    messagingSenderId: '982208266428',
    projectId: 'sehatsaja-2',
    authDomain: 'sehatsaja-2.firebaseapp.com',
    storageBucket: 'sehatsaja-2.firebasestorage.app',
    measurementId: 'G-2P65PDLVTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRTUp_LIvQrKX6TH94aGW3YDsVopq9NEY',
    appId: '1:982208266428:android:6aa3fe0cd6e5d7e1a650b9',
    messagingSenderId: '982208266428',
    projectId: 'sehatsaja-2',
    storageBucket: 'sehatsaja-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01baTfXoRTTE1UR1RXy3-4Lk7AAiJ3Cs',
    appId: '1:982208266428:ios:036bc9c2731e5d34a650b9',
    messagingSenderId: '982208266428',
    projectId: 'sehatsaja-2',
    storageBucket: 'sehatsaja-2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01baTfXoRTTE1UR1RXy3-4Lk7AAiJ3Cs',
    appId: '1:982208266428:ios:036bc9c2731e5d34a650b9',
    messagingSenderId: '982208266428',
    projectId: 'sehatsaja-2',
    storageBucket: 'sehatsaja-2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxLhBJu-2ZsH6FbaCh0fzcOQ7wfnIAZfs',
    appId: '1:982208266428:web:b54934342072dccfa650b9',
    messagingSenderId: '982208266428',
    projectId: 'sehatsaja-2',
    authDomain: 'sehatsaja-2.firebaseapp.com',
    storageBucket: 'sehatsaja-2.firebasestorage.app',
    measurementId: 'G-2X2XWNXYMP',
  );
}
